# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# Triggers
trigger:
- master

# Pools
pool:
  vmImage: 'ubuntu-latest'

# Steps
steps:

# Say hello
- script: echo Hello, ICT DevOps!
  displayName: 'Say hello'

# Start the build process
- script: bash build.sh
  displayName: 'Run build script'


#archive
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'web/'
    includeRootFolder: true
    archiveType: 'tar'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true


#release
- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'github.com_nooryousef'
    repositoryName: 'nooryousef/devops-ci-demo'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'gitTag'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'




# Start the deployment process
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'su-DevOps@40.85.183.109'
    sourceFolder: 'web/'
    contents: '**'
    targetFolder: '/var/www/html/'
    readyTimeout: '20000'


